### ISSUE TITLE
Possible to allow for .NETStandard2.0 assemblies

### ISSUE THREAD

**Issue by mwpowellhtx** [microsoft/MSBuildLocator#78] opened 2019-10-25 15:04 UTC
That is the question, whether it is possible to allow for `netstandard2.0`. We are working on a compilation manager fixture and, apparently, we need to align with an appropriate SDK instance. The rub in our case is that our fixture assemby(ies) are ostensibly targeting `netstandard2.0`. I suppose we could target `netcoreapp2.1` in a pinch if that's what it took to work through the issue as we are interested more in the build fixture operating in a run time, but the surface area is interesting for wider potential application. Thoughts? Recommendations? Thank you..

**Comment by rainersigwald** [comment] 2019-10-25 15:06
No, this isn't possible. Details: https://github.com/microsoft/MSBuildLocator/issues/62#issuecomment-470987522

**Comment by rainersigwald** [comment] 2019-10-25 15:06
Duplicate of #62

**Closed by rainersigwald** 2019-10-25 15:06 UTC
